import enum


class AnalysisStatus(str, enum.Enum):
    SAFE = "SAFE"
    SUSPICIOUS = "SUSPICIOUS"
    DANGEROUS = "DANGEROUS"
    UNKNOWN = "UNKNOWN"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_CONTENT = "INSUFFICIENT_CONTENT"


class ThreatType(str, enum.Enum):
    PHISHING = "PHISHING"
    SOCIAL_ENGINEERING = "SOCIAL_ENGINEERING"
    URGENT_ACTION = "URGENT_ACTION"
    SUSPICIOUS_REQUEST = "SUSPICIOUS_REQUEST"
    MALICIOUS_LINK = "MALICIOUS_LINK"
    SENSITIVE_DATA_REQUEST = "SENSITIVE_DATA_REQUEST"
    OTHER = "OTHER"
    NONE = "NONE"


class AnalysisSource(str, enum.Enum):
    NOTIFICATION = "NOTIFICATION"
    MANUAL = "MANUAL"
    LINK_GATE = "LINK_GATE"
